openapi: '3.0.2'
info:
  title: Simple Mocroservice
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      parameters:
        - in: query
          name: param
          schema:
            type: string
          example: bar
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  importantProperty:
                    type: string